name: snowflake_telco_lab
version: 1.0.0
config-version: 2

profile: telco

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
clean-targets:
  - target
  - dbt_packages
  - logs

models:
  snowflake_telco_lab:
    +persist_docs:
      relation: true
      columns: true
    staging:
      +materialized: view
      +tags: ["telco", "snowflake", "staging"]

