-- schema_comments
COMMENT ON SCHEMA "TELCO_LAB"."TELCO_STAGE_LOAD" IS 'Snowflake landing schema for deterministic telco seed files. Tables in this schema preserve source-shaped records for downstream staging in dbt and governance demonstrations in Horizon.
';

-- table_comments
COMMENT ON TABLE "TELCO_LAB"."TELCO_STAGE_LOAD"."party" IS 'Master registry for parties in the telco operating model.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."party"."party_id" IS 'Stable synthetic identifier for the party record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."party"."party_type" IS 'Party category such as individual or organization.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."party"."status" IS 'Lifecycle status assigned to the party record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."party"."created_at" IS 'Timestamp when the synthetic party record was created.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."party"."updated_at" IS 'Timestamp of the most recent update applied to the party record.';
COMMENT ON TABLE "TELCO_LAB"."TELCO_STAGE_LOAD"."individual" IS 'Individual customer details linked to a party.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."individual"."individual_id" IS 'Stable synthetic identifier for the individual record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."individual"."party_id" IS 'Reference back to the owning party record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."individual"."first_name" IS 'Synthetic given name for the individual.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."individual"."last_name" IS 'Synthetic family name for the individual.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."individual"."email" IS 'Synthetic email address used for governance and classification demos.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."individual"."date_of_birth" IS 'Synthetic date of birth for the customer record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."individual"."created_at" IS 'Timestamp when the individual record was created.';
COMMENT ON TABLE "TELCO_LAB"."TELCO_STAGE_LOAD"."account" IS 'Billing and service account records for parties.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."account"."account_id" IS 'Stable synthetic identifier for the account.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."account"."party_id" IS 'Party that owns the account.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."account"."account_number" IS 'Human-readable account number used in operations.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."account"."account_type" IS 'Type of account such as business, individual, or prepaid.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."account"."status" IS 'Current lifecycle status of the account.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."account"."created_at" IS 'Timestamp when the account record was created.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."account"."closed_at" IS 'Timestamp when the account was closed, if applicable.';
COMMENT ON TABLE "TELCO_LAB"."TELCO_STAGE_LOAD"."product_offering" IS 'Sellable product plans and add-on offerings.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."product_offering"."product_offering_id" IS 'Stable synthetic identifier for the product offering.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."product_offering"."name" IS 'Marketing-facing name for the plan or bundle.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."product_offering"."category" IS 'Product category such as data plan, bundle, or voice.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."product_offering"."data_limit_gb" IS 'Included data limit in gigabytes when applicable.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."product_offering"."voice_limit_min" IS 'Included voice minutes when applicable.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."product_offering"."price_chf" IS 'Recurring product price expressed in Swiss francs.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."product_offering"."status" IS 'Commercial status of the product offering.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."product_offering"."created_at" IS 'Timestamp when the product offering was introduced.';
COMMENT ON TABLE "TELCO_LAB"."TELCO_STAGE_LOAD"."service" IS 'Active service instances provisioned for accounts.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."service"."service_id" IS 'Stable synthetic identifier for the service instance.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."service"."account_id" IS 'Account that owns the service instance.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."service"."service_type" IS 'Technical or commercial type of service being delivered.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."service"."status" IS 'Current provisioning or lifecycle status of the service.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."service"."activated_at" IS 'Timestamp when the service became active.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."service"."terminated_at" IS 'Timestamp when the service terminated, if applicable.';
COMMENT ON TABLE "TELCO_LAB"."TELCO_STAGE_LOAD"."subscription" IS 'Subscriptions that connect services to product offerings.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."subscription"."subscription_id" IS 'Stable synthetic identifier for the subscription.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."subscription"."service_id" IS 'Service instance covered by the subscription.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."subscription"."product_offering_id" IS 'Product offering attached to the subscription.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."subscription"."status" IS 'Subscription lifecycle status.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."subscription"."start_date" IS 'Subscription start date.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."subscription"."end_date" IS 'Subscription end date, when present.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."subscription"."renewal_date" IS 'Planned renewal date for the subscription.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."subscription"."created_at" IS 'Timestamp when the subscription record was created.';
COMMENT ON TABLE "TELCO_LAB"."TELCO_STAGE_LOAD"."device" IS 'Devices registered against customer accounts.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."device"."device_id" IS 'Stable synthetic identifier for the registered device.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."device"."account_id" IS 'Account linked to the device registration.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."device"."device_type" IS 'Device category such as smartphone, tablet, or router.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."device"."manufacturer" IS 'Device manufacturer name.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."device"."model" IS 'Device model name.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."device"."imei" IS 'Synthetic equipment identifier associated with the device.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."device"."status" IS 'Registration status of the device.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."device"."registered_at" IS 'Timestamp when the device was registered.';
COMMENT ON TABLE "TELCO_LAB"."TELCO_STAGE_LOAD"."sim_card" IS 'SIM assignments that link accounts and devices.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."sim_card"."sim_id" IS 'Stable synthetic identifier for the SIM assignment.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."sim_card"."account_id" IS 'Account associated with the SIM card.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."sim_card"."device_id" IS 'Device currently paired with the SIM card.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."sim_card"."msisdn" IS 'Synthetic dialable mobile number tied to the SIM card.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."sim_card"."iccid" IS 'Synthetic integrated circuit card identifier for the SIM.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."sim_card"."status" IS 'Operational status of the SIM card.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."sim_card"."activated_at" IS 'Timestamp when the SIM card was activated.';
COMMENT ON TABLE "TELCO_LAB"."TELCO_STAGE_LOAD"."usage_event" IS 'Usage records for data, voice, and messaging events.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."usage_event"."usage_id" IS 'Stable synthetic identifier for the raw usage event.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."usage_event"."account_id" IS 'Account that incurred the usage event.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."usage_event"."service_id" IS 'Service instance that produced the usage event.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."usage_event"."usage_type" IS 'Usage category such as data, voice, or SMS.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."usage_event"."quantity" IS 'Measured usage quantity for the event.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."usage_event"."event_timestamp" IS 'Event timestamp captured from the synthetic source.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."usage_event"."rating_status" IS 'Status of downstream rating for the usage event.';
COMMENT ON TABLE "TELCO_LAB"."TELCO_STAGE_LOAD"."app_event" IS 'Digital engagement events emitted by the telco application.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."app_event"."app_event_id" IS 'Stable synthetic identifier for the app event.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."app_event"."account_id" IS 'Account associated with the digital event.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."app_event"."device_id" IS 'Device associated with the app session.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."app_event"."event_type" IS 'Digital event type such as login, browse, or support contact.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."app_event"."session_minutes" IS 'Session duration captured for the event.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."app_event"."event_timestamp" IS 'Timestamp when the app event occurred.';
COMMENT ON TABLE "TELCO_LAB"."TELCO_STAGE_LOAD"."invoice" IS 'Monthly billing invoices produced for accounts.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."invoice"."invoice_id" IS 'Stable synthetic identifier for the invoice.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."invoice"."account_id" IS 'Account billed by the invoice.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."invoice"."invoice_number" IS 'Human-readable invoice number.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."invoice"."invoice_date" IS 'Invoice issue date.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."invoice"."due_date" IS 'Invoice due date.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."invoice"."total_amount_chf" IS 'Total invoice amount in Swiss francs.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."invoice"."status" IS 'Invoice payment status.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."invoice"."created_at" IS 'Timestamp when the invoice record was created.';
COMMENT ON TABLE "TELCO_LAB"."TELCO_STAGE_LOAD"."payment" IS 'Payments received against invoices.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."payment"."payment_id" IS 'Stable synthetic identifier for the payment.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."payment"."invoice_id" IS 'Invoice settled by the payment.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."payment"."amount_chf" IS 'Paid amount in Swiss francs.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."payment"."payment_method" IS 'Method used to settle the invoice.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."payment"."payment_date" IS 'Date when payment was captured.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."payment"."status" IS 'Processing status for the payment.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."payment"."created_at" IS 'Timestamp when the payment record was created.';
COMMENT ON TABLE "TELCO_LAB"."TELCO_STAGE_LOAD"."agreement" IS 'Agreements and contracts related to customer accounts.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."agreement"."agreement_id" IS 'Stable synthetic identifier for the agreement.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."agreement"."account_id" IS 'Account covered by the agreement.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."agreement"."agreement_type" IS 'Agreement category such as service contract or data processing terms.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."agreement"."status" IS 'Current status of the agreement.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."agreement"."signed_date" IS 'Date when the agreement was signed.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."agreement"."effective_date" IS 'Effective date of the agreement.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."agreement"."termination_date" IS 'Termination date of the agreement, when present.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."agreement"."created_at" IS 'Timestamp when the agreement record was created.';
COMMENT ON TABLE "TELCO_LAB"."TELCO_STAGE_LOAD"."service_order" IS 'Requests to activate, modify, or cancel services.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."service_order"."order_id" IS 'Stable synthetic identifier for the service order.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."service_order"."account_id" IS 'Account requesting the service order.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."service_order"."order_type" IS 'Requested order action such as activation or suspension.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."service_order"."status" IS 'Current fulfillment status of the order.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."service_order"."order_date" IS 'Timestamp when the order was submitted.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."service_order"."fulfillment_date" IS 'Timestamp when fulfillment completed.';
COMMENT ON TABLE "TELCO_LAB"."TELCO_STAGE_LOAD"."geographic_address" IS 'Address inventory for party billing, installation, and service locations.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."geographic_address"."address_id" IS 'Stable synthetic identifier for the geographic address record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."geographic_address"."party_id" IS 'Reference to the related party record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."geographic_address"."address_role" IS 'Business attribute for address role on the geographic address record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."geographic_address"."street_name" IS 'Synthetic address attribute for the geographic address record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."geographic_address"."city" IS 'Synthetic address attribute for the geographic address record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."geographic_address"."region_code" IS 'Synthetic address attribute for the geographic address record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."geographic_address"."postal_code" IS 'Synthetic address attribute for the geographic address record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."geographic_address"."country_code" IS 'Synthetic address attribute for the geographic address record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."geographic_address"."valid_from" IS 'Date value for valid from on the geographic address record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."geographic_address"."valid_to" IS 'Date value for valid to on the geographic address record.';
COMMENT ON TABLE "TELCO_LAB"."TELCO_STAGE_LOAD"."contact_medium" IS 'Preferred contact channels and contact details for each party.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."contact_medium"."contact_medium_id" IS 'Stable synthetic identifier for the contact medium record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."contact_medium"."party_id" IS 'Reference to the related party record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."contact_medium"."medium_type" IS 'Business attribute for medium type on the contact medium record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."contact_medium"."medium_value" IS 'Synthetic contact detail captured for the selected contact medium.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."contact_medium"."usage_purpose" IS 'Business attribute for usage purpose on the contact medium record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."contact_medium"."preference_rank" IS 'Business attribute for preference rank on the contact medium record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."contact_medium"."valid_from" IS 'Date value for valid from on the contact medium record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."contact_medium"."valid_to" IS 'Date value for valid to on the contact medium record.';
COMMENT ON TABLE "TELCO_LAB"."TELCO_STAGE_LOAD"."party_role" IS 'Party-to-account role assignments such as customer, billing contact, or technical contact.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."party_role"."party_role_id" IS 'Stable synthetic identifier for the party role record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."party_role"."party_id" IS 'Reference to the related party record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."party_role"."account_id" IS 'Reference to the related account record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."party_role"."role_type" IS 'Business attribute for role type on the party role record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."party_role"."status" IS 'Lifecycle or operational status for the party role record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."party_role"."assigned_at" IS 'Timestamp when the party role record was created or assigned.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."party_role"."revoked_at" IS 'Business attribute for revoked at on the party role record.';
COMMENT ON TABLE "TELCO_LAB"."TELCO_STAGE_LOAD"."product_inventory" IS 'Customer-owned product instances derived from commercial product offerings.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."product_inventory"."product_id" IS 'Stable synthetic identifier for the product inventory record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."product_inventory"."account_id" IS 'Reference to the related account record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."product_inventory"."product_offering_id" IS 'Reference to the related product offering record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."product_inventory"."service_id" IS 'Reference to the related service record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."product_inventory"."status" IS 'Lifecycle or operational status for the product inventory record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."product_inventory"."activated_at" IS 'Timestamp when the product inventory record was created or assigned.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."product_inventory"."terminated_at" IS 'Timestamp describing when the terminated at occurred.';
COMMENT ON TABLE "TELCO_LAB"."TELCO_STAGE_LOAD"."resource" IS 'Assigned technical resources that support provisioned services.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."resource"."resource_id" IS 'Stable synthetic identifier for the resource record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."resource"."service_id" IS 'Reference to the related service record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."resource"."resource_type" IS 'Business attribute for resource type on the resource record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."resource"."resource_name" IS 'Descriptive attribute for resource.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."resource"."resource_status" IS 'Lifecycle or operational status for the resource record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."resource"."assigned_at" IS 'Timestamp when the resource record was created or assigned.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."resource"."released_at" IS 'Business attribute for released at on the resource record.';
COMMENT ON TABLE "TELCO_LAB"."TELCO_STAGE_LOAD"."customer_interaction" IS 'Sales and support interactions across assisted and digital channels.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."customer_interaction"."interaction_id" IS 'Stable synthetic identifier for the customer interaction record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."customer_interaction"."account_id" IS 'Reference to the related account record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."customer_interaction"."service_id" IS 'Reference to the related service record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."customer_interaction"."channel" IS 'Business attribute for channel on the customer interaction record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."customer_interaction"."interaction_type" IS 'Business attribute for interaction type on the customer interaction record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."customer_interaction"."outcome" IS 'Business attribute for outcome on the customer interaction record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."customer_interaction"."interaction_timestamp" IS 'Timestamp describing when the interaction timestamp occurred.';
COMMENT ON TABLE "TELCO_LAB"."TELCO_STAGE_LOAD"."trouble_ticket" IS 'Support tickets raised for billing, connectivity, and service-quality issues.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."trouble_ticket"."ticket_id" IS 'Stable synthetic identifier for the trouble ticket record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."trouble_ticket"."account_id" IS 'Reference to the related account record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."trouble_ticket"."service_id" IS 'Reference to the related service record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."trouble_ticket"."ticket_category" IS 'Business attribute for ticket category on the trouble ticket record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."trouble_ticket"."severity" IS 'Business attribute for severity on the trouble ticket record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."trouble_ticket"."status" IS 'Lifecycle or operational status for the trouble ticket record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."trouble_ticket"."opened_at" IS 'Timestamp describing when the opened at occurred.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."trouble_ticket"."resolved_at" IS 'Timestamp describing when the resolved at occurred.';
COMMENT ON TABLE "TELCO_LAB"."TELCO_STAGE_LOAD"."service_lifecycle_event" IS 'Lifecycle history for operational services, including activation and change events.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."service_lifecycle_event"."lifecycle_event_id" IS 'Stable synthetic identifier for the service lifecycle event record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."service_lifecycle_event"."service_id" IS 'Reference to the related service record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."service_lifecycle_event"."event_type" IS 'Business attribute for event type on the service lifecycle event record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."service_lifecycle_event"."event_reason" IS 'Descriptive attribute for service lifecycle event.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."service_lifecycle_event"."actor_type" IS 'Business attribute for actor type on the service lifecycle event record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."service_lifecycle_event"."event_timestamp" IS 'Timestamp describing when the event timestamp occurred.';
COMMENT ON TABLE "TELCO_LAB"."TELCO_STAGE_LOAD"."invoice_charge" IS 'Detailed charge lines that roll up into customer invoices.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."invoice_charge"."charge_id" IS 'Stable synthetic identifier for the invoice charge record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."invoice_charge"."invoice_id" IS 'Reference to the related invoice record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."invoice_charge"."charge_type" IS 'Business attribute for charge type on the invoice charge record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."invoice_charge"."charge_description" IS 'Descriptive attribute for invoice charge.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."invoice_charge"."quantity" IS 'Measured quantity captured in quantity.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."invoice_charge"."amount_chf" IS 'Synthetic monetary value expressed in Swiss francs.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."invoice_charge"."charge_date" IS 'Date value for charge date on the invoice charge record.';
