-- schema_comments
COMMENT ON SCHEMA "TELCO_LAB"."TELCO_STAGE_LOAD" IS 'Snowflake landing schema for deterministic telco seed files. Tables in this schema preserve source-shaped records for downstream staging in dbt and governance demonstrations in Horizon.
';

-- table_comments
COMMENT ON TABLE "TELCO_LAB"."TELCO_STAGE_LOAD"."PARTY" IS 'Master registry for parties in the telco operating model.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."PARTY"."PARTY_ID" IS 'Stable synthetic identifier for the party record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."PARTY"."PARTY_TYPE" IS 'Party category such as individual or organization.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."PARTY"."STATUS" IS 'Lifecycle status assigned to the party record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."PARTY"."CREATED_AT" IS 'Timestamp when the synthetic party record was created.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."PARTY"."UPDATED_AT" IS 'Timestamp of the most recent update applied to the party record.';
COMMENT ON TABLE "TELCO_LAB"."TELCO_STAGE_LOAD"."INDIVIDUAL" IS 'Individual customer details linked to a party.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."INDIVIDUAL"."INDIVIDUAL_ID" IS 'Stable synthetic identifier for the individual record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."INDIVIDUAL"."PARTY_ID" IS 'Reference back to the owning party record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."INDIVIDUAL"."FIRST_NAME" IS 'Synthetic given name for the individual.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."INDIVIDUAL"."LAST_NAME" IS 'Synthetic family name for the individual.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."INDIVIDUAL"."EMAIL" IS 'Synthetic email address used for governance and classification demos.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."INDIVIDUAL"."DATE_OF_BIRTH" IS 'Synthetic date of birth for the customer record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."INDIVIDUAL"."CREATED_AT" IS 'Timestamp when the individual record was created.';
COMMENT ON TABLE "TELCO_LAB"."TELCO_STAGE_LOAD"."ACCOUNT" IS 'Billing and service account records for parties.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."ACCOUNT"."ACCOUNT_ID" IS 'Stable synthetic identifier for the account.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."ACCOUNT"."PARTY_ID" IS 'Party that owns the account.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."ACCOUNT"."ACCOUNT_NUMBER" IS 'Human-readable account number used in operations.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."ACCOUNT"."ACCOUNT_TYPE" IS 'Type of account such as business, individual, or prepaid.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."ACCOUNT"."STATUS" IS 'Current lifecycle status of the account.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."ACCOUNT"."CREATED_AT" IS 'Timestamp when the account record was created.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."ACCOUNT"."CLOSED_AT" IS 'Timestamp when the account was closed, if applicable.';
COMMENT ON TABLE "TELCO_LAB"."TELCO_STAGE_LOAD"."PRODUCT_OFFERING" IS 'Sellable product plans and add-on offerings.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."PRODUCT_OFFERING"."PRODUCT_OFFERING_ID" IS 'Stable synthetic identifier for the product offering.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."PRODUCT_OFFERING"."NAME" IS 'Marketing-facing name for the plan or bundle.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."PRODUCT_OFFERING"."CATEGORY" IS 'Product category such as data plan, bundle, or voice.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."PRODUCT_OFFERING"."DATA_LIMIT_GB" IS 'Included data limit in gigabytes when applicable.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."PRODUCT_OFFERING"."VOICE_LIMIT_MIN" IS 'Included voice minutes when applicable.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."PRODUCT_OFFERING"."PRICE_CHF" IS 'Recurring product price expressed in Swiss francs.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."PRODUCT_OFFERING"."STATUS" IS 'Commercial status of the product offering.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."PRODUCT_OFFERING"."CREATED_AT" IS 'Timestamp when the product offering was introduced.';
COMMENT ON TABLE "TELCO_LAB"."TELCO_STAGE_LOAD"."SERVICE" IS 'Active service instances provisioned for accounts.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."SERVICE"."SERVICE_ID" IS 'Stable synthetic identifier for the service instance.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."SERVICE"."ACCOUNT_ID" IS 'Account that owns the service instance.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."SERVICE"."SERVICE_TYPE" IS 'Technical or commercial type of service being delivered.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."SERVICE"."STATUS" IS 'Current provisioning or lifecycle status of the service.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."SERVICE"."ACTIVATED_AT" IS 'Timestamp when the service became active.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."SERVICE"."TERMINATED_AT" IS 'Timestamp when the service terminated, if applicable.';
COMMENT ON TABLE "TELCO_LAB"."TELCO_STAGE_LOAD"."SUBSCRIPTION" IS 'Subscriptions that connect services to product offerings.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."SUBSCRIPTION"."SUBSCRIPTION_ID" IS 'Stable synthetic identifier for the subscription.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."SUBSCRIPTION"."SERVICE_ID" IS 'Service instance covered by the subscription.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."SUBSCRIPTION"."PRODUCT_OFFERING_ID" IS 'Product offering attached to the subscription.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."SUBSCRIPTION"."STATUS" IS 'Subscription lifecycle status.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."SUBSCRIPTION"."START_DATE" IS 'Subscription start date.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."SUBSCRIPTION"."END_DATE" IS 'Subscription end date, when present.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."SUBSCRIPTION"."RENEWAL_DATE" IS 'Planned renewal date for the subscription.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."SUBSCRIPTION"."CREATED_AT" IS 'Timestamp when the subscription record was created.';
COMMENT ON TABLE "TELCO_LAB"."TELCO_STAGE_LOAD"."DEVICE" IS 'Devices registered against customer accounts.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."DEVICE"."DEVICE_ID" IS 'Stable synthetic identifier for the registered device.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."DEVICE"."ACCOUNT_ID" IS 'Account linked to the device registration.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."DEVICE"."DEVICE_TYPE" IS 'Device category such as smartphone, tablet, or router.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."DEVICE"."MANUFACTURER" IS 'Device manufacturer name.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."DEVICE"."MODEL" IS 'Device model name.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."DEVICE"."IMEI" IS 'Synthetic equipment identifier associated with the device.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."DEVICE"."STATUS" IS 'Registration status of the device.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."DEVICE"."REGISTERED_AT" IS 'Timestamp when the device was registered.';
COMMENT ON TABLE "TELCO_LAB"."TELCO_STAGE_LOAD"."SIM_CARD" IS 'SIM assignments that link accounts and devices.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."SIM_CARD"."SIM_ID" IS 'Stable synthetic identifier for the SIM assignment.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."SIM_CARD"."ACCOUNT_ID" IS 'Account associated with the SIM card.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."SIM_CARD"."DEVICE_ID" IS 'Device currently paired with the SIM card.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."SIM_CARD"."MSISDN" IS 'Synthetic dialable mobile number tied to the SIM card.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."SIM_CARD"."ICCID" IS 'Synthetic integrated circuit card identifier for the SIM.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."SIM_CARD"."STATUS" IS 'Operational status of the SIM card.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."SIM_CARD"."ACTIVATED_AT" IS 'Timestamp when the SIM card was activated.';
COMMENT ON TABLE "TELCO_LAB"."TELCO_STAGE_LOAD"."USAGE_EVENT" IS 'Usage records for data, voice, and messaging events.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."USAGE_EVENT"."USAGE_ID" IS 'Stable synthetic identifier for the raw usage event.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."USAGE_EVENT"."ACCOUNT_ID" IS 'Account that incurred the usage event.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."USAGE_EVENT"."SERVICE_ID" IS 'Service instance that produced the usage event.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."USAGE_EVENT"."USAGE_TYPE" IS 'Usage category such as data, voice, or SMS.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."USAGE_EVENT"."QUANTITY" IS 'Measured usage quantity for the event.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."USAGE_EVENT"."EVENT_TIMESTAMP" IS 'Event timestamp captured from the synthetic source.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."USAGE_EVENT"."RATING_STATUS" IS 'Status of downstream rating for the usage event.';
COMMENT ON TABLE "TELCO_LAB"."TELCO_STAGE_LOAD"."APP_EVENT" IS 'Digital engagement events emitted by the telco application.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."APP_EVENT"."APP_EVENT_ID" IS 'Stable synthetic identifier for the app event.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."APP_EVENT"."ACCOUNT_ID" IS 'Account associated with the digital event.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."APP_EVENT"."DEVICE_ID" IS 'Device associated with the app session.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."APP_EVENT"."EVENT_TYPE" IS 'Digital event type such as login, browse, or support contact.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."APP_EVENT"."SESSION_MINUTES" IS 'Session duration captured for the event.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."APP_EVENT"."EVENT_TIMESTAMP" IS 'Timestamp when the app event occurred.';
COMMENT ON TABLE "TELCO_LAB"."TELCO_STAGE_LOAD"."INVOICE" IS 'Monthly billing invoices produced for accounts.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."INVOICE"."INVOICE_ID" IS 'Stable synthetic identifier for the invoice.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."INVOICE"."ACCOUNT_ID" IS 'Account billed by the invoice.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."INVOICE"."INVOICE_NUMBER" IS 'Human-readable invoice number.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."INVOICE"."INVOICE_DATE" IS 'Invoice issue date.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."INVOICE"."DUE_DATE" IS 'Invoice due date.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."INVOICE"."TOTAL_AMOUNT_CHF" IS 'Total invoice amount in Swiss francs.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."INVOICE"."STATUS" IS 'Invoice payment status.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."INVOICE"."CREATED_AT" IS 'Timestamp when the invoice record was created.';
COMMENT ON TABLE "TELCO_LAB"."TELCO_STAGE_LOAD"."PAYMENT" IS 'Payments received against invoices.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."PAYMENT"."PAYMENT_ID" IS 'Stable synthetic identifier for the payment.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."PAYMENT"."INVOICE_ID" IS 'Invoice settled by the payment.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."PAYMENT"."AMOUNT_CHF" IS 'Paid amount in Swiss francs.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."PAYMENT"."PAYMENT_METHOD" IS 'Method used to settle the invoice.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."PAYMENT"."PAYMENT_DATE" IS 'Date when payment was captured.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."PAYMENT"."STATUS" IS 'Processing status for the payment.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."PAYMENT"."CREATED_AT" IS 'Timestamp when the payment record was created.';
COMMENT ON TABLE "TELCO_LAB"."TELCO_STAGE_LOAD"."AGREEMENT" IS 'Agreements and contracts related to customer accounts.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."AGREEMENT"."AGREEMENT_ID" IS 'Stable synthetic identifier for the agreement.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."AGREEMENT"."ACCOUNT_ID" IS 'Account covered by the agreement.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."AGREEMENT"."AGREEMENT_TYPE" IS 'Agreement category such as service contract or data processing terms.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."AGREEMENT"."STATUS" IS 'Current status of the agreement.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."AGREEMENT"."SIGNED_DATE" IS 'Date when the agreement was signed.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."AGREEMENT"."EFFECTIVE_DATE" IS 'Effective date of the agreement.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."AGREEMENT"."TERMINATION_DATE" IS 'Termination date of the agreement, when present.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."AGREEMENT"."CREATED_AT" IS 'Timestamp when the agreement record was created.';
COMMENT ON TABLE "TELCO_LAB"."TELCO_STAGE_LOAD"."SERVICE_ORDER" IS 'Requests to activate, modify, or cancel services.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."SERVICE_ORDER"."ORDER_ID" IS 'Stable synthetic identifier for the service order.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."SERVICE_ORDER"."ACCOUNT_ID" IS 'Account requesting the service order.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."SERVICE_ORDER"."ORDER_TYPE" IS 'Requested order action such as activation or suspension.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."SERVICE_ORDER"."STATUS" IS 'Current fulfillment status of the order.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."SERVICE_ORDER"."ORDER_DATE" IS 'Timestamp when the order was submitted.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."SERVICE_ORDER"."FULFILLMENT_DATE" IS 'Timestamp when fulfillment completed.';
COMMENT ON TABLE "TELCO_LAB"."TELCO_STAGE_LOAD"."GEOGRAPHIC_ADDRESS" IS 'Address inventory for party billing, installation, and service locations.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."GEOGRAPHIC_ADDRESS"."ADDRESS_ID" IS 'Stable synthetic identifier for the geographic address record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."GEOGRAPHIC_ADDRESS"."PARTY_ID" IS 'Reference to the related party record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."GEOGRAPHIC_ADDRESS"."ADDRESS_ROLE" IS 'Business attribute for address role on the geographic address record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."GEOGRAPHIC_ADDRESS"."STREET_NAME" IS 'Synthetic address attribute for the geographic address record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."GEOGRAPHIC_ADDRESS"."CITY" IS 'Synthetic address attribute for the geographic address record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."GEOGRAPHIC_ADDRESS"."REGION_CODE" IS 'Synthetic address attribute for the geographic address record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."GEOGRAPHIC_ADDRESS"."POSTAL_CODE" IS 'Synthetic address attribute for the geographic address record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."GEOGRAPHIC_ADDRESS"."COUNTRY_CODE" IS 'Synthetic address attribute for the geographic address record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."GEOGRAPHIC_ADDRESS"."VALID_FROM" IS 'Date value for valid from on the geographic address record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."GEOGRAPHIC_ADDRESS"."VALID_TO" IS 'Date value for valid to on the geographic address record.';
COMMENT ON TABLE "TELCO_LAB"."TELCO_STAGE_LOAD"."CONTACT_MEDIUM" IS 'Preferred contact channels and contact details for each party.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."CONTACT_MEDIUM"."CONTACT_MEDIUM_ID" IS 'Stable synthetic identifier for the contact medium record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."CONTACT_MEDIUM"."PARTY_ID" IS 'Reference to the related party record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."CONTACT_MEDIUM"."MEDIUM_TYPE" IS 'Business attribute for medium type on the contact medium record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."CONTACT_MEDIUM"."MEDIUM_VALUE" IS 'Synthetic contact detail captured for the selected contact medium.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."CONTACT_MEDIUM"."USAGE_PURPOSE" IS 'Business attribute for usage purpose on the contact medium record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."CONTACT_MEDIUM"."PREFERENCE_RANK" IS 'Business attribute for preference rank on the contact medium record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."CONTACT_MEDIUM"."VALID_FROM" IS 'Date value for valid from on the contact medium record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."CONTACT_MEDIUM"."VALID_TO" IS 'Date value for valid to on the contact medium record.';
COMMENT ON TABLE "TELCO_LAB"."TELCO_STAGE_LOAD"."PARTY_ROLE" IS 'Party-to-account role assignments such as customer, billing contact, or technical contact.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."PARTY_ROLE"."PARTY_ROLE_ID" IS 'Stable synthetic identifier for the party role record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."PARTY_ROLE"."PARTY_ID" IS 'Reference to the related party record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."PARTY_ROLE"."ACCOUNT_ID" IS 'Reference to the related account record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."PARTY_ROLE"."ROLE_TYPE" IS 'Business attribute for role type on the party role record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."PARTY_ROLE"."STATUS" IS 'Lifecycle or operational status for the party role record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."PARTY_ROLE"."ASSIGNED_AT" IS 'Timestamp when the party role record was created or assigned.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."PARTY_ROLE"."REVOKED_AT" IS 'Business attribute for revoked at on the party role record.';
COMMENT ON TABLE "TELCO_LAB"."TELCO_STAGE_LOAD"."PRODUCT_INVENTORY" IS 'Customer-owned product instances derived from commercial product offerings.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."PRODUCT_INVENTORY"."PRODUCT_ID" IS 'Stable synthetic identifier for the product inventory record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."PRODUCT_INVENTORY"."ACCOUNT_ID" IS 'Reference to the related account record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."PRODUCT_INVENTORY"."PRODUCT_OFFERING_ID" IS 'Reference to the related product offering record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."PRODUCT_INVENTORY"."SERVICE_ID" IS 'Reference to the related service record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."PRODUCT_INVENTORY"."STATUS" IS 'Lifecycle or operational status for the product inventory record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."PRODUCT_INVENTORY"."ACTIVATED_AT" IS 'Timestamp when the product inventory record was created or assigned.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."PRODUCT_INVENTORY"."TERMINATED_AT" IS 'Timestamp describing when the terminated at occurred.';
COMMENT ON TABLE "TELCO_LAB"."TELCO_STAGE_LOAD"."RESOURCE" IS 'Assigned technical resources that support provisioned services.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."RESOURCE"."RESOURCE_ID" IS 'Stable synthetic identifier for the resource record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."RESOURCE"."SERVICE_ID" IS 'Reference to the related service record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."RESOURCE"."RESOURCE_TYPE" IS 'Business attribute for resource type on the resource record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."RESOURCE"."RESOURCE_NAME" IS 'Descriptive attribute for resource.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."RESOURCE"."RESOURCE_STATUS" IS 'Lifecycle or operational status for the resource record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."RESOURCE"."ASSIGNED_AT" IS 'Timestamp when the resource record was created or assigned.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."RESOURCE"."RELEASED_AT" IS 'Business attribute for released at on the resource record.';
COMMENT ON TABLE "TELCO_LAB"."TELCO_STAGE_LOAD"."CUSTOMER_INTERACTION" IS 'Sales and support interactions across assisted and digital channels.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."CUSTOMER_INTERACTION"."INTERACTION_ID" IS 'Stable synthetic identifier for the customer interaction record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."CUSTOMER_INTERACTION"."ACCOUNT_ID" IS 'Reference to the related account record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."CUSTOMER_INTERACTION"."SERVICE_ID" IS 'Reference to the related service record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."CUSTOMER_INTERACTION"."CHANNEL" IS 'Business attribute for channel on the customer interaction record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."CUSTOMER_INTERACTION"."INTERACTION_TYPE" IS 'Business attribute for interaction type on the customer interaction record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."CUSTOMER_INTERACTION"."OUTCOME" IS 'Business attribute for outcome on the customer interaction record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."CUSTOMER_INTERACTION"."INTERACTION_TIMESTAMP" IS 'Timestamp describing when the interaction timestamp occurred.';
COMMENT ON TABLE "TELCO_LAB"."TELCO_STAGE_LOAD"."TROUBLE_TICKET" IS 'Support tickets raised for billing, connectivity, and service-quality issues.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."TROUBLE_TICKET"."TICKET_ID" IS 'Stable synthetic identifier for the trouble ticket record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."TROUBLE_TICKET"."ACCOUNT_ID" IS 'Reference to the related account record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."TROUBLE_TICKET"."SERVICE_ID" IS 'Reference to the related service record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."TROUBLE_TICKET"."TICKET_CATEGORY" IS 'Business attribute for ticket category on the trouble ticket record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."TROUBLE_TICKET"."SEVERITY" IS 'Business attribute for severity on the trouble ticket record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."TROUBLE_TICKET"."STATUS" IS 'Lifecycle or operational status for the trouble ticket record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."TROUBLE_TICKET"."OPENED_AT" IS 'Timestamp describing when the opened at occurred.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."TROUBLE_TICKET"."RESOLVED_AT" IS 'Timestamp describing when the resolved at occurred.';
COMMENT ON TABLE "TELCO_LAB"."TELCO_STAGE_LOAD"."SERVICE_LIFECYCLE_EVENT" IS 'Lifecycle history for operational services, including activation and change events.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."SERVICE_LIFECYCLE_EVENT"."LIFECYCLE_EVENT_ID" IS 'Stable synthetic identifier for the service lifecycle event record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."SERVICE_LIFECYCLE_EVENT"."SERVICE_ID" IS 'Reference to the related service record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."SERVICE_LIFECYCLE_EVENT"."EVENT_TYPE" IS 'Business attribute for event type on the service lifecycle event record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."SERVICE_LIFECYCLE_EVENT"."EVENT_REASON" IS 'Descriptive attribute for service lifecycle event.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."SERVICE_LIFECYCLE_EVENT"."ACTOR_TYPE" IS 'Business attribute for actor type on the service lifecycle event record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."SERVICE_LIFECYCLE_EVENT"."EVENT_TIMESTAMP" IS 'Timestamp describing when the event timestamp occurred.';
COMMENT ON TABLE "TELCO_LAB"."TELCO_STAGE_LOAD"."INVOICE_CHARGE" IS 'Detailed charge lines that roll up into customer invoices.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."INVOICE_CHARGE"."CHARGE_ID" IS 'Stable synthetic identifier for the invoice charge record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."INVOICE_CHARGE"."INVOICE_ID" IS 'Reference to the related invoice record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."INVOICE_CHARGE"."CHARGE_TYPE" IS 'Business attribute for charge type on the invoice charge record.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."INVOICE_CHARGE"."CHARGE_DESCRIPTION" IS 'Descriptive attribute for invoice charge.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."INVOICE_CHARGE"."QUANTITY" IS 'Measured quantity captured in quantity.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."INVOICE_CHARGE"."AMOUNT_CHF" IS 'Synthetic monetary value expressed in Swiss francs.';
COMMENT ON COLUMN "TELCO_LAB"."TELCO_STAGE_LOAD"."INVOICE_CHARGE"."CHARGE_DATE" IS 'Date value for charge date on the invoice charge record.';
