from __future__ import annotations

import argparse
import base64
import http.cookiejar
import os
import sys
import urllib.error
import urllib.parse
import urllib.request
from dataclasses import dataclass
from pathlib import Path
from textwrap import dedent

from local_env_utils import parse_env_file


REPO_ROOT = Path(__file__).resolve().parents[1]
ENV_FILE = REPO_ROOT / ".env"
JENKINS_ENV_FILE = REPO_ROOT / ".env.jenkins"


@dataclass(frozen=True)
class ScenarioConfig:
    scenario: str
    job_name: str
    script_path: str
    description: str


SCENARIOS: dict[str, ScenarioConfig] = {
    "A1": ScenarioConfig(
        scenario="A1",
        job_name="A1-external-reference",
        script_path="variants/A1-external-reference/Jenkinsfile",
        description="Ready-made external-reference variant (A1). Jenkinsfile generated by fluid generate ci.",
    ),
    "A2": ScenarioConfig(
        scenario="A2",
        job_name="A2-internal-reference",
        script_path="variants/A2-internal-reference/Jenkinsfile",
        description="Ready-made internal-reference variant (A2). Jenkinsfile generated by fluid generate ci.",
    ),
}

CONTAINER_REPO_URL = "/workspace/gitlab/path-a-telco-silver-product-demo/.git"


def load_env() -> dict[str, str]:
    merged = parse_env_file(ENV_FILE)
    merged.update(parse_env_file(JENKINS_ENV_FILE))
    merged.update({key: value for key, value in os.environ.items() if value})
    return merged


def resolve_workspaces_dir(env: dict[str, str]) -> Path:
    raw = env.get("DEMO_WORKSPACES_DIR", "").strip()
    if not raw:
        return REPO_ROOT / "gitlab"

    candidate = Path(raw).expanduser()
    if candidate.is_absolute():
        return candidate
    return (REPO_ROOT / candidate).resolve()


def build_request(
    url: str,
    user: str,
    password: str,
    method: str = "GET",
    data: bytes | None = None,
    extra_headers: dict[str, str] | None = None,
) -> urllib.request.Request:
    token = base64.b64encode(f"{user}:{password}".encode("utf-8")).decode("ascii")
    headers = {"Authorization": f"Basic {token}"}
    if extra_headers:
        headers.update(extra_headers)
    return urllib.request.Request(url, data=data, headers=headers, method=method)


def open_request(
    opener: urllib.request.OpenerDirector, request: urllib.request.Request
) -> urllib.response.addinfourl:
    return opener.open(request)


def fetch_crumb(
    opener: urllib.request.OpenerDirector,
    base_url: str,
    user: str,
    password: str,
) -> dict[str, str]:
    crumb_url = (
        base_url
        + "/crumbIssuer/api/xml?xpath="
        + urllib.parse.quote('concat(//crumbRequestField,":",//crumb)')
    )
    request = build_request(crumb_url, user, password)
    try:
        with open_request(opener, request) as response:
            payload = response.read().decode("utf-8").strip()
    except urllib.error.HTTPError as exc:
        if exc.code == 404:
            return {}
        raise

    header, _, value = payload.partition(":")
    if not header or not value:
        raise RuntimeError(f"Unexpected crumb response from Jenkins: {payload!r}")
    return {header: value}


def job_exists(
    opener: urllib.request.OpenerDirector,
    base_url: str,
    user: str,
    password: str,
    job_name: str,
) -> bool:
    url = base_url + f"/job/{urllib.parse.quote(job_name)}/api/json"
    request = build_request(url, user, password)
    try:
        with open_request(opener, request):
            return True
    except urllib.error.HTTPError as exc:
        if exc.code == 404:
            return False
        raise


def build_job_config(scenario: ScenarioConfig) -> bytes:
    xml = dedent(
        f"""\
        <?xml version="1.0" encoding="UTF-8"?>
        <flow-definition>
          <actions/>
          <description>{scenario.description}</description>
          <keepDependencies>false</keepDependencies>
          <properties/>
          <triggers/>
          <definition class="org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition">
            <scriptPath>{scenario.script_path}</scriptPath>
            <lightweight>false</lightweight>
            <scm class="hudson.plugins.git.GitSCM">
              <userRemoteConfigs>
                <hudson.plugins.git.UserRemoteConfig>
                  <url>{CONTAINER_REPO_URL}</url>
                </hudson.plugins.git.UserRemoteConfig>
              </userRemoteConfigs>
              <branches>
                <hudson.plugins.git.BranchSpec>
                  <name>*/main</name>
                </hudson.plugins.git.BranchSpec>
              </branches>
              <configVersion>2</configVersion>
              <doGenerateSubmoduleConfigurations>false</doGenerateSubmoduleConfigurations>
              <gitTool>Default</gitTool>
            </scm>
          </definition>
        </flow-definition>
        """
    )
    return xml.encode("utf-8")


def post_xml(
    opener: urllib.request.OpenerDirector,
    url: str,
    user: str,
    password: str,
    data: bytes,
    crumb_headers: dict[str, str],
) -> None:
    headers = {"Content-Type": "application/xml"}
    headers.update(crumb_headers)
    request = build_request(url, user, password, method="POST", data=data, extra_headers=headers)
    with open_request(opener, request):
        return


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Create or update the lab's Jenkins Pipeline-from-SCM job for scenario A1 or A2."
    )
    parser.add_argument("--scenario", required=True, choices=sorted(SCENARIOS))
    args = parser.parse_args()

    scenario = SCENARIOS[args.scenario]
    env = load_env()
    jenkins_url = env.get("JENKINS_URL", "http://localhost:8081/").strip() or "http://localhost:8081/"
    jenkins_url = jenkins_url.rstrip("/")
    jenkins_user = env.get("JENKINS_ADMIN_ID", "admin").strip() or "admin"
    jenkins_password = env.get("JENKINS_ADMIN_PASSWORD", "").strip()
    if not jenkins_password:
        raise RuntimeError(
            "JENKINS_ADMIN_PASSWORD is empty. Set it in .env, .env.jenkins, or the current shell."
        )
    opener = urllib.request.build_opener(
        urllib.request.HTTPCookieProcessor(http.cookiejar.CookieJar())
    )

    workspaces_dir = resolve_workspaces_dir(env)
    repo_root = workspaces_dir / "path-a-telco-silver-product-demo"
    host_git_dir = repo_root / ".git"
    host_script_path = repo_root / scenario.script_path

    if not repo_root.exists():
        raise FileNotFoundError(
            f"Expected workspace repo at {repo_root}. Run `task workspaces:bootstrap` first."
        )
    if not host_git_dir.exists():
        raise FileNotFoundError(
            f"Expected git metadata at {host_git_dir}. The workspace repo is not ready for Jenkins."
        )
    if not host_script_path.exists():
        raise FileNotFoundError(
            f"Expected generated Jenkinsfile at {host_script_path}. Run `fluid generate ci ... --out Jenkinsfile` first."
        )

    print(f"Preparing Jenkins sync for scenario {scenario.scenario}")
    print(f"Jenkins URL: {jenkins_url}")
    print(f"Job name: {scenario.job_name}")
    print(f"SCM repo: {CONTAINER_REPO_URL}")
    print(f"Script path: {scenario.script_path}")
    print(f"Validated host repo: {repo_root}")
    print(f"Validated host Jenkinsfile: {host_script_path}")

    crumb_headers = fetch_crumb(opener, jenkins_url, jenkins_user, jenkins_password)
    config_xml = build_job_config(scenario)
    exists = job_exists(opener, jenkins_url, jenkins_user, jenkins_password, scenario.job_name)

    if exists:
        print("Action: update existing Pipeline-from-SCM job")
        post_xml(
            opener,
            jenkins_url + f"/job/{urllib.parse.quote(scenario.job_name)}/config.xml",
            jenkins_user,
            jenkins_password,
            config_xml,
            crumb_headers,
        )
    else:
        print("Action: create new Pipeline-from-SCM job")
        post_xml(
            opener,
            jenkins_url + f"/createItem?name={urllib.parse.quote(scenario.job_name)}",
            jenkins_user,
            jenkins_password,
            config_xml,
            crumb_headers,
        )

    print("Jenkins sync complete. No build was triggered.")


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:  # pragma: no cover - CLI failure path
        print(str(exc), file=sys.stderr)
        sys.exit(1)
